### PR TITLE
Added new journals, conferences, workshops and a summer school

### PR DESCRIPTION
**Pull request by angelosalatino**

### CODE REVIEW

**Review by napsternxg — COMMENTED** [review]
Thanks. Can you also update the table of contents. I will merge it then.

**Comment by angelosalatino** [comment]
Hi Shubhanshu, I updated the ToC too.
I just added Summer Schools as a new heading.

**Comment by napsternxg** [comment]
Thanks @angelosalatino :-)

**Comment by angelosalatino** [comment]
I have other things in mind. Soon I will add more things. cool stuff

**Pull request merged**
