### PR TITLE
Add infolis

### PR DESCRIPTION
**Pull request by zuphilip**

### CODE REVIEW

**Comment by napsternxg** [comment]
@zuphilip can you provide more details about this URL. I couldn't understand much from visiting the link.

**Comment by zuphilip** [comment]
Sure, let me try:

The infolis project is about mining papers and analyzing which data studies or data source they used in the paper. Nowadays, this could also be just a proper data citation. However, most often in practice the mention of the used data is not very normed and maybe just somewhere in text abbreviated in some way. That is the challenge where a bootstrap algorithm applies some known pattern resp. search for new patterns alternatively.

Does this make more sense?

There is the website http://infolis.github.io/ with information, already captured data and the possibility to analyze your pdfs and interact with the API. The complete code is open source and available at GitHub https://github.com/infolis/ . However, setting up and running another instance might be non-trivial, but there is also some dockerization which should make deployment easier.

**Comment by napsternxg** [comment]
@zuphilip ok I understand it better now. However, when I tried to upload a paper of mine which refers to the SemEval dataset, I couldn't understand the output. 

Details here: http://infolis.gesis.org/infolink/api/infolisFile/a54e7520-ac37-11e6-9137-197c3cf429df

**Comment by zuphilip** [comment]
The result after upload is just a reference with some infos. Afterwards you can use this reference to call the next algorithm text-extraction, which then can be used for the next algorithms. It might be easier to use the Datasetifier directly for a test: http://infolis.gesis.org/infolink/play/datasetifier. However, there was a recent changed in the development and it might be that currently not all steps are adapted to this change. CC @kba

**Comment by kba** [comment]
Great to see interest in Infolis! We're currently putting the final touches on some code and cleaning/reloading data, so the platform is a bit shaky at the moment, e.g. the list of patternsets in the datasetifier is outdated at the moment.

We'll report back here once things settle down.

CC @bolandka @dommii

**Comment by napsternxg** [comment]
@zuphilip thanks for the details. I have just updated the README file and I think this link is more appropriate for the newly added Tools section. Can you make that change. Then I will merge your pull request.

**Comment by zuphilip** [comment]
Okay, I rebased the PR and moved the line under `Tools` section.

**Pull request merged**
